// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-jTLVQsmCTsyG-sR2eLVGndyWaFZ1jfw',
    appId: '1:587725584732:web:3dc69a4e52d5d54855e999',
    messagingSenderId: '587725584732',
    projectId: 'crusine-connect',
    authDomain: 'crusine-connect.firebaseapp.com',
    storageBucket: 'crusine-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-7wv6QlT90mSJob20EFv52EYMqPNGJkU',
    appId: '1:587725584732:android:76c041516fb0a68055e999',
    messagingSenderId: '587725584732',
    projectId: 'crusine-connect',
    storageBucket: 'crusine-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCvDxDwHF6Ae2z1E0mzAV_IcJLM3Uw9QE',
    appId: '1:587725584732:ios:bb9f8bcc650ebcfe55e999',
    messagingSenderId: '587725584732',
    projectId: 'crusine-connect',
    storageBucket: 'crusine-connect.firebasestorage.app',
    iosBundleId: 'com.example.cuisineconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCvDxDwHF6Ae2z1E0mzAV_IcJLM3Uw9QE',
    appId: '1:587725584732:ios:bb9f8bcc650ebcfe55e999',
    messagingSenderId: '587725584732',
    projectId: 'crusine-connect',
    storageBucket: 'crusine-connect.firebasestorage.app',
    iosBundleId: 'com.example.cuisineconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-jTLVQsmCTsyG-sR2eLVGndyWaFZ1jfw',
    appId: '1:587725584732:web:862bf6e28859dfe555e999',
    messagingSenderId: '587725584732',
    projectId: 'crusine-connect',
    authDomain: 'crusine-connect.firebaseapp.com',
    storageBucket: 'crusine-connect.firebasestorage.app',
  );

}